import { useEffect, useMemo, useState } from 'react';
import { listen } from '@tauri-apps/api/event';
import { invoke } from '@tauri-apps/api/core';
import { Activity, ArrowDown, ArrowUp, Boxes, Globe2, LayoutDashboard, ListFilter, Monitor, Radio, Search, Settings2, ShieldCheck, Wifi, X } from 'lucide-react';

type View = 'Overview'|'Devices'|'Traffic'|'Packets'|'Services';
type Device={name:string;ip:string;vendor:string;traffic:string;status:'Online'|'Idle';service:string;color:string;mac?:string};
type BackendDevice={ip:string;mac:string;hostname?:string;vendor:string;status:string};
type Packet={timestamp:string;source:string;destination:string;protocol:string;size:number;service:string;confidence:number};
type ProcessConnection={process:string;pid:number;protocol:string;local_address:string;remote_address:string;state:string};
type Network={connected:boolean;interface:string;local_ip?:string;gateway?:string;capture_interface?:string;capture_available:boolean};

export default function App(){
 const [view,setView]=useState<View>('Overview'); const [expert,setExpert]=useState(false); const [query,setQuery]=useState('');
 const [selected,setSelected]=useState<Device|null>(null); const [selectedPacket,setSelectedPacket]=useState<Packet|null>(null);
 const [devices,setDevices]=useState<Device[]>([]); const [packets,setPackets]=useState<Packet[]>([]); const [processes,setProcesses]=useState<ProcessConnection[]>([]);
 const [capture,setCapture]=useState(false); const [captureError,setCaptureError]=useState('');
 const [network,setNetwork]=useState<Network>({connected:false,interface:'Unknown',capture_available:false});

 const refreshProcesses=async()=>{try{setProcesses(await invoke<ProcessConnection[]>('process_connections'))}catch{setProcesses([])}};
 const refreshDevices=async()=>{try{const raw=await invoke<BackendDevice[]>('discover_devices');setDevices(raw.map((d,i)=>({name:d.hostname||`Device ${i+1}`,ip:d.ip,vendor:d.vendor,mac:d.mac,traffic:'0 B',status:d.status==='Online'?'Online':'Idle',service:'Unknown',color:i%2?'#4EA1FF':'#35F2C1'})))}catch{setDevices([])}};

 useEffect(()=>{let cleanups:(()=>void)[]=[];let timer:number|undefined;
  (async()=>{try{const n=await invoke<Network>('network_state');setNetwork(n);await refreshDevices();await refreshProcesses();
    const unlistenPacket=await listen<Packet>('capture:packet',e=>setPackets(p=>[e.payload,...p].slice(0,500)));
    const unlistenState=await listen<{active:boolean}>('capture:state',e=>setCapture(e.payload.active));
    const unlistenError=await listen<{message:string}>('capture:error',e=>{setCaptureError(e.payload.message);setCapture(false)});
    cleanups=[unlistenPacket,unlistenState,unlistenError];
    timer=window.setInterval(refreshDevices,5000);
  }catch(e){setCaptureError(String(e))}})();
  return()=>{cleanups.forEach(c=>c?.());if(timer)window.clearInterval(timer)};
 },[]);

 const visibleDevices=useMemo(()=>devices.map(d=>{const related=packets.filter(p=>p.source===d.ip||p.destination===d.ip);const bytes=related.reduce((n,p)=>n+p.size,0);const services=related.reduce<Record<string,number>>((a,p)=>(a[p.service]=(a[p.service]||0)+1,a),{});const top=Object.entries(services).sort((a,b)=>b[1]-a[1])[0]?.[0]||'Unknown';return {...d,traffic:formatBytes(bytes),service:top}}),[devices,packets]);
 const packetDevice=(p:Packet)=>visibleDevices.find(d=>d.ip===p.source)||visibleDevices.find(d=>d.ip===p.destination)||((network.local_ip===p.source||network.local_ip===p.destination)?{name:'This PC',ip:network.local_ip||'Local'}:undefined);
 const filtered=useMemo(()=>visibleDevices.filter(d=>(d.name+d.ip+d.vendor+d.service).toLowerCase().includes(query.toLowerCase())),[visibleDevices,query]);
 const nav:[View,typeof LayoutDashboard][]=[['Overview',LayoutDashboard],['Devices',Monitor],['Traffic',Activity],['Packets',Radio],['Services',Globe2]];
 const start=async()=>{setCaptureError('');setPackets([]);try{await invoke('start_capture',{interface:network.capture_interface||null})}catch(e){setCaptureError(String(e))}};
 const stop=async()=>{try{await invoke('stop_capture')}finally{setCapture(false)}};
 const total=packets.reduce((n,p)=>n+p.size,0);
 return <div className="app"><aside className="sidebar"><div className="brand"><img src="/assets/brand/logo-mark.svg"/><div><strong>NETSIGHT</strong><small>Know what's moving.</small></div></div><div className="nav">{nav.map(([name,Icon])=><button className={view===name?'active':''} onClick={()=>setView(name)} key={name}><Icon size={18}/><span>{name}</span></button>)}</div><div className="side-bottom"><div className="capture"><span className={capture?'live-dot':'live-dot off'}/><div><b>{capture?'Capture active':'Capture stopped'}</b><small>{network.interface} · {network.local_ip||'Network unavailable'}</small></div></div><button className="settings"><Settings2 size={17}/> Settings</button></div></aside>
 <main className="main"><header className="topbar"><div><div className="eyebrow">{network.interface.toUpperCase()} / {capture?'LIVE':'IDLE'}</div><h1>{view}</h1></div><div className="top-actions"><div className="network-pill"><Wifi size={16}/><span>{network.connected?'Connected':'Offline'}</span><i/></div><button className={expert?'mode expert':'mode'} onClick={()=>setExpert(!expert)}>{expert?'Expert':'Easy'} Mode</button></div></header>
 {captureError&&<div className="notice"><ShieldCheck size={16}/><span>{captureError}</span><button onClick={()=>setCaptureError('')}><X size={15}/></button></div>}
 {view==='Overview'&&<Overview devices={visibleDevices} packets={packets} capture={capture} total={total} onSelect={setSelected} onStart={start} onStop={stop}/>} {view==='Devices'&&<Devices devices={filtered} query={query} setQuery={setQuery} onSelect={setSelected}/>} {view==='Traffic'&&<Traffic packets={packets} devices={visibleDevices} packetDevice={packetDevice}/>} {view==='Packets'&&<Packets packets={packets} packetDevice={packetDevice} onSelect={setSelectedPacket}/>} {view==='Services'&&<Services packets={packets} processes={processes} onRefresh={refreshProcesses}/>}</main>
 {selected&&<DeviceDrawer device={selected} onClose={()=>setSelected(null)}/>} {selectedPacket&&<PacketInspector packet={selectedPacket} device={packetDevice(selectedPacket)} onClose={()=>setSelectedPacket(null)}/>}</div>
}

function Overview({devices,packets,capture,total,onSelect,onStart,onStop}:{devices:Device[];packets:Packet[];capture:boolean;total:number;onSelect:(d:Device)=>void;onStart:()=>void;onStop:()=>void}){const top=packets.reduce<Record<string,number>>((a,p)=>(a[p.service]=(a[p.service]||0)+p.size,a),{});const services=Object.entries(top).sort((a,b)=>b[1]-a[1]).slice(0,4);return <div className="content"><section className="hero-card"><div><div className="eyebrow">NETWORK OVERVIEW</div><h2>Everything visible.<br/><em>Nothing guessed.</em></h2><p>Live packet metadata, devices and evidence-based service signals.</p><button className="hero-action" onClick={capture?onStop:onStart}>{capture?'Stop capture':'Start live capture'} <Radio size={15}/></button></div><div className="hero-orb"><Radio size={52}/><span/></div></section><div className="stats"><Stat icon={Boxes} label="Devices" value={String(devices.length)} note="currently reachable"/><Stat icon={ArrowDown} label="Traffic" value={formatBytes(total)} note="captured"/><Stat icon={Activity} label="Packets" value={String(packets.length)} note="recent events"/><Stat icon={Globe2} label="Services" value={String(services.length)} note="identified signals"/></div><div className="grid-two"><section className="panel traffic-panel"><div className="panel-head"><div><div className="eyebrow">LIVE TRAFFIC</div><h3>Packet activity</h3></div><span className="live-badge"><i/> {capture?'LIVE':'IDLE'}</span></div><div className="traffic-total"><b>{formatBytes(total)}</b><span>observed</span></div><Sparkline packets={packets}/><div className="legend"><span><i className="mint"/>Packets</span><span className="muted">Latest {packets.length}</span></div></section><section className="panel"><div className="panel-head"><div><div className="eyebrow">TOP SERVICES</div><h3>What's moving</h3></div></div>{services.length?services.map(([s,n])=><div className="service-mini" key={s}><b>{s}</b><span>{formatBytes(n)}</span><strong>{s==='Unknown'?'—':'Observed'}</strong></div>):<Empty text="Start capture to identify services."/>}</section></div><section className="panel"><div className="panel-head"><div><div className="eyebrow">REACHABLE DEVICES</div><h3>Who's online</h3></div></div><div className="device-row head"><span>DEVICE</span><span>IP ADDRESS</span><span>SERVICE</span><span>TRAFFIC</span></div>{devices.slice(0,8).map(d=><div className="device-row" key={d.ip} onClick={()=>onSelect(d)}><span className="device-name"><i style={{background:d.color}}/>{d.name}</span><span className="muted">{d.ip}</span><span><span className="service-tag">{d.service}</span></span><span>{d.traffic}</span></div>)}{!devices.length&&<Empty text="No reachable LAN devices found."/>}</section></div>}
function Sparkline({packets}:{packets:Packet[]}){const heights=Array.from({length:15},(_,i)=>Math.max(18,Math.min(100,20+(packets[i]?.size||i*31)%80)));return <div className="sparkline">{heights.map((h,i)=><span key={i} style={{height:`${h}%`}}/>)}</div>}
function Stat({icon:Icon,label,value,note}:{icon:any;label:string;value:string;note:string}){return <div className="stat"><Icon size={18}/><div><small>{label}</small><b>{value}</b><span>{note}</span></div></div>}
function Devices({devices,query,setQuery,onSelect}:{devices:Device[];query:string;setQuery:(s:string)=>void;onSelect:(d:Device)=>void}){return <div className="content"><div className="toolbar"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search devices..."/></div><button className="filter"><ListFilter size={16}/> Reachable</button></div><section className="panel"><div className="device-row head"><span>DEVICE</span><span>IP ADDRESS</span><span>VENDOR</span><span>TRAFFIC</span></div>{devices.map(d=><div className="device-row" key={d.ip} onClick={()=>onSelect(d)}><span className="device-name"><i style={{background:d.color}}/><b>{d.name}</b><small>{d.status}</small></span><span className="muted">{d.ip}</span><span>{d.vendor}</span><span>{d.traffic}</span></div>)}{!devices.length&&<Empty text="No reachable devices found."/>}</section></div>}
function Traffic({packets,devices,packetDevice}:{packets:Packet[];devices:Device[];packetDevice:(p:Packet)=>Device|{name:string;ip:string}|undefined}){const total=packets.reduce((n,p)=>n+p.size,0);const grouped=packets.reduce<Record<string,{name:string;bytes:number;count:number}>>((a,p)=>{const d=packetDevice(p);if(!d)return a;const x=a[d.ip]||{name:d.name,bytes:0,count:0};x.bytes+=p.size;x.count++;a[d.ip]=x;return a},{});return <div className="content"><section className="panel large-chart"><div className="panel-head"><div><div className="eyebrow">LIVE TRAFFIC</div><h3>Observed traffic</h3></div><span className="live-badge"><i/> LIVE</span></div><div className="big-number">{formatBytes(total)} <small>captured</small></div><Sparkline packets={packets}/><div className="traffic-cards"><div><ArrowDown/><small>PACKETS</small><b>{packets.length}</b></div><div><ArrowUp/><small>BYTES</small><b>{formatBytes(total)}</b></div></div></section><section className="panel"><div className="panel-head"><div><div className="eyebrow">DEVICE TRAFFIC</div><h3>Traffic by device</h3></div></div><div className="device-row head"><span>DEVICE</span><span>IP ADDRESS</span><span>PACKETS</span><span>TRAFFIC</span></div>{Object.entries(grouped).sort((a,b)=>b[1].bytes-a[1].bytes).map(([ip,x])=><div className="device-row" key={ip}><span className="device-name"><i/>{x.name}</span><span className="muted">{ip}</span><span>{x.count}</span><span>{formatBytes(x.bytes)}</span></div>)}{!Object.keys(grouped).length&&<Empty text="Capture traffic to see which device generated it."/>}</section></div>}
function Packets({packets,packetDevice,onSelect}:{packets:Packet[];packetDevice:(p:Packet)=>Device|{name:string;ip:string}|undefined;onSelect:(p:Packet)=>void}){return <div className="content"><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search packets..."/></div><div className="filter-group"><button className="chip active">All</button><button className="chip">TCP</button><button className="chip">UDP</button><button className="chip">DNS</button><button className="chip">TLS</button></div></div><section className="panel packet-panel"><div className="packet-head"><span>TIME</span><span>DEVICE</span><span>SOURCE</span><span>DESTINATION</span><span>PROTO</span><span>SIZE</span></div>{packets.slice(0,150).map((p,i)=>{const d=packetDevice(p);return <button className="packet-row packet-click" key={`${p.timestamp}-${i}`} onClick={()=>onSelect(p)}><span>{formatTimestamp(p.timestamp)}</span><span>{d?.name||'Unknown device'}</span><span>{p.source}</span><span>{p.destination}</span><span className="proto">{p.protocol}{p.service!=='Unknown'?` · ${p.service}`:''}</span><span>{formatBytes(p.size)}</span></button>})}{!packets.length&&<Empty text="No packets yet. Start live capture."/>}</section></div>}
function DeviceDrawer({device,onClose}:{device:Device;onClose:()=>void}){return <div className="drawer-backdrop" onClick={onClose}><section className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X size={18}/></button><div className="device-orb"><Monitor size={30}/></div><div className="eyebrow">DEVICE / OBSERVED</div><h2>{device.name}</h2><p className="muted">{device.vendor} · {device.ip}</p><div className="detail-grid"><div><small>STATUS</small><b>{device.status}</b></div><div><small>MAC</small><b>{device.mac||'Unknown'}</b></div><div><small>TRAFFIC</small><b>{device.traffic}</b></div><div><small>SERVICE</small><b>{device.service}</b></div></div><div className="evidence"><ShieldCheck size={17}/><span>Device status comes from the active Windows neighbor table. Service labels use observable DNS, TLS and port evidence.</span></div></section></div>}
function PacketInspector({packet,device,onClose}:{packet:Packet;device:Device|{name:string;ip:string}|undefined;onClose:()=>void}){const confidence=packet.confidence?`${packet.confidence}%`:'Unknown';const method=packet.service==='Unknown'?'No sufficient evidence':'DNS / TLS / port intelligence';return <div className="drawer-backdrop" onClick={onClose}><section className="drawer packet-inspector" onClick={e=>e.stopPropagation()}><button className="close" onClick={onClose}><X size={18}/></button><div className="packet-orb"><Radio size={25}/></div><div className="eyebrow">PACKET / INSPECTOR</div><h2>{packet.service==='Unknown'?'Unknown traffic':packet.service}</h2><p className="muted">{packet.protocol} · {formatBytes(packet.size)} · captured metadata</p><div className="inspector-section"><span className="inspector-title">DEVICE</span><div className="endpoint"><small>ASSOCIATED DEVICE</small><b>{device?.name||'Unknown device'}</b><span>{device?.ip||'No LAN match'}</span></div><span className="inspector-title">ENDPOINTS</span><div className="endpoint"><small>SOURCE</small><b>{packet.source}</b></div><div className="endpoint"><small>DESTINATION</small><b>{packet.destination}</b></div></div><div className="inspector-grid"><div><small>PROTOCOL</small><b>{packet.protocol}</b></div><div><small>SIZE</small><b>{formatBytes(packet.size)}</b></div><div><small>SERVICE</small><b>{packet.service}</b></div><div><small>CONFIDENCE</small><b>{confidence}</b></div></div><div className="evidence"><ShieldCheck size={17}/><div><b>Detection evidence</b><span>{method}</span></div></div><div className="privacy-note">Payload contents are not decrypted. NETSIGHT explains observable metadata and keeps encrypted content opaque.</div></section></div>}
function Services({packets,processes,onRefresh}:{packets:Packet[];processes:ProcessConnection[];onRefresh:()=>void}){const grouped=packets.reduce<Record<string,{bytes:number;count:number;confidence:number}>>((a,p)=>{const x=a[p.service]||{bytes:0,count:0,confidence:0};x.bytes+=p.size;x.count++;x.confidence=Math.max(x.confidence,p.confidence);a[p.service]=x;return a},{});const appMap=new Map<string,ProcessConnection[]>();processes.forEach(p=>{const arr=appMap.get(p.process)||[];arr.push(p);appMap.set(p.process,arr)});return <div className="content"><section className="panel"><div className="panel-head"><div><div className="eyebrow">LOCAL APP INTELLIGENCE</div><h3>Applications → connections</h3></div><button className="filter" onClick={onRefresh}>Refresh</button></div>{processes.length?<div className="app-list">{Array.from(appMap.entries()).slice(0,12).map(([name,rows])=><div className="app-row" key={name}><div><b>{name}</b><small>PID {rows[0].pid} · {rows[0].protocol}</small></div><div><span>{rows[0].remote_address}</span><small>{rows.length} observed connection{rows.length===1?'':'s'}</small></div><strong>Observed</strong></div>)}</div>:<Empty text="No local process connections available."/>}</section><section className="panel"><div className="panel-head"><div><div className="eyebrow">SERVICE DETECTION</div><h3>Recognized services</h3></div><span className="confidence"><ShieldCheck size={15}/> Evidence-based</span></div><div className="service-table head"><span>SERVICE</span><span>PACKETS</span><span>TRAFFIC</span><span>CONFIDENCE</span><span>METHOD</span></div>{Object.entries(grouped).sort((a,b)=>b[1].bytes-a[1].bytes).map(([name,x])=><div className="service-table" key={name}><span className="service-name"><i/>{name}</span><span>{x.count}</span><span>{formatBytes(x.bytes)}</span><span><b className={x.confidence===0?'unknown':''}>{x.confidence?`${x.confidence}%`:'—'}</b></span><span className="muted">DNS / TLS / ports</span></div>)}{!Object.keys(grouped).length&&<Empty text="Service signals appear here as packets are observed."/>}</section></div>}
function Empty({text}:{text:string}){return <div className="empty"><Radio size={24}/><b>{text}</b></div>}
function formatBytes(n:number){if(n<1024)return `${n} B`;if(n<1024*1024)return `${(n/1024).toFixed(1)} KB`;return `${(n/1024/1024).toFixed(1)} MB`}
function formatTimestamp(ms:string){const n=Number(ms);if(!Number.isFinite(n))return ms;return new Date(n).toLocaleTimeString()}
