import { useEffect, useMemo, useState } from 'react';
import { listen } from '@tauri-apps/api/event';
import { invoke } from '@tauri-apps/api/core';
import { Activity, ArrowDown, ArrowUp, Boxes, Globe2, LayoutDashboard, ListFilter, Monitor, Network, Radio, Search, Server, Settings2, ShieldCheck, Wifi, X } from 'lucide-react';

type View = 'Overview'|'Devices'|'Traffic'|'Packets'|'Services';
type Device={name:string;ip:string;vendor:string;traffic:string;status:'Online'|'Idle';service:string;color:string};
type BackendDevice={ip:string;mac:string;hostname?:string;vendor:string;status:string};
type Packet={timestamp:string;source:string;destination:string;protocol:string;size:number;service:string;confidence:number};
const fallbackDevices:Device[]=[{name:'NETSIGHT',ip:'127.0.0.1',vendor:'Local host',traffic:'—',status:'Online',service:'Local',color:'#35F2C1'}];

export default function App(){
 const [view,setView]=useState<View>('Overview'); const [expert,setExpert]=useState(false); const [query,setQuery]=useState(''); const [selected,setSelected]=useState<Device|null>(null); const [devices,setDevices]=useState<Device[]>(fallbackDevices); const [packets,setPackets]=useState<Packet[]>([]); const [capture,setCapture]=useState(false); const [captureError,setCaptureError]=useState(''); const [network,setNetwork]=useState<{connected:boolean;local_ip?:string;gateway?:string}>({connected:false});
 useEffect(()=>{let cleanups:(()=>void)[]=[]; (async()=>{try{const n=await invoke<typeof network>('network_state');setNetwork(n); const raw=await invoke<BackendDevice[]>('discover_devices'); setDevices(raw.map((d,i)=>({name:d.hostname||`Device ${i+1}`,ip:d.ip,vendor:d.vendor,traffic:'—',status:d.status==='Online'?'Online':'Idle',service:'Unknown',color:i%2?'#4EA1FF':'#35F2C1'}))); const unlistenPacket=await listen<Packet>('capture:packet',e=>{setPackets(p=>[e.payload,...p].slice(0,250));}); const unlistenState=await listen<{active:boolean}>('capture:state',e=>setCapture(e.payload.active)); const unlistenError=await listen<{message:string}>('capture:error',e=>{setCaptureError(e.payload.message);setCapture(false);}); cleanups=[unlistenPacket,unlistenState,unlistenError]; try{await invoke('start_capture',{interface:null});}catch(e){setCaptureError(String(e));}}catch(e){setCaptureError(String(e));}})(); return()=>cleanups.forEach(c=>c?.());},[]);
 const filtered=useMemo(()=>devices.filter(d=>(d.name+d.ip+d.vendor+d.service).toLowerCase().includes(query.toLowerCase())),[devices,query]);
 const nav:[View,typeof LayoutDashboard][]=[['Overview',LayoutDashboard],['Devices',Monitor],['Traffic',Activity],['Packets',Radio],['Services',Globe2]];
 const stop=async()=>{await invoke('stop_capture');setCapture(false)}; const start=async()=>{setCaptureError('');try{await invoke('start_capture',{interface:null})}catch(e){setCaptureError(String(e))}};
 return <div className="app"><aside className="sidebar"><div className="brand"><img src="/assets/brand/logo-mark.svg"/><div><strong>NETSIGHT</strong><small>Know what's moving.</small></div></div><div className="nav">{nav.map(([name,Icon])=><button className={view===name?'active':''} onClick={()=>setView(name)} key={name}><Icon size={18}/><span>{name}</span></button>)}</div><div className="side-bottom"><div className="capture"><span className={capture?'live-dot':'live-dot off'}/><div><b>{capture?'Capture active':'Capture stopped'}</b><small>{network.local_ip||'Network unavailable'}</small></div></div><button className="settings"><Settings2 size={17}/> Settings</button></div></aside>
 <main className="main"><header className="topbar"><div><div className="eyebrow">LOCAL NETWORK / {capture?'LIVE':'IDLE'}</div><h1>{view}</h1></div><div className="top-actions"><div className="network-pill"><Wifi size={16}/><span>{network.connected?'Wi-Fi':'Offline'}</span><i/></div><button className={expert?'mode expert':'mode'} onClick={()=>setExpert(!expert)}>{expert?'Expert':'Easy'} Mode</button></div></header>
 {captureError&&<div className="notice"><ShieldCheck size={16}/><span>{captureError}</span><button onClick={()=>setCaptureError('')}><X size={15}/></button></div>}
 {view==='Overview'&&<Overview devices={devices} packets={packets} capture={capture} onSelect={setSelected} onStart={start} onStop={stop}/>} {view==='Devices'&&<Devices devices={filtered} query={query} setQuery={setQuery} onSelect={setSelected}/>} {view==='Traffic'&&<Traffic packets={packets}/>} {view==='Packets'&&<Packets packets={packets}/>} {view==='Services'&&<Services packets={packets}/>}</main>
 {selected&&<div className="drawer-backdrop" onClick={()=>setSelected(null)}><section className="drawer" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setSelected(null)}><X size={18}/></button><div className="device-orb"><Monitor size={30}/></div><div className="eyebrow">DEVICE / OBSERVED</div><h2>{selected.name}</h2><p className="muted">{selected.vendor} · {selected.ip}</p><div className="detail-grid"><div><small>STATUS</small><b>{selected.status}</b></div><div><small>TRAFFIC</small><b>{selected.traffic}</b></div><div><small>SERVICE</small><b>{selected.service}</b></div><div><small>CONFIDENCE</small><b>{selected.service==='Unknown'?'—':'Observable'}</b></div></div><div className="evidence"><ShieldCheck size={17}/><span>NETSIGHT only reports observable metadata. HTTPS payloads are not decrypted.</span></div></section></div>}
 </div>
}

function Overview({devices,packets,capture,onSelect,onStart,onStop}:{devices:Device[];packets:Packet[];capture:boolean;onSelect:(d:Device)=>void;onStart:()=>void;onStop:()=>void}){const total=packets.reduce((n,p)=>n+p.size,0);const top=packets.reduce<Record<string,number>>((a,p)=>(a[p.service]=(a[p.service]||0)+p.size,a),{});const services=Object.entries(top).sort((a,b)=>b[1]-a[1]).slice(0,4);return <div className="content"><section className="hero-card"><div><div className="eyebrow">NETWORK OVERVIEW</div><h2>Everything visible.<br/><em>Nothing guessed.</em></h2><p>Live packet metadata, devices and service signals — explained clearly.</p><button className="hero-action" onClick={capture?onStop:onStart}>{capture?'Stop capture':'Start live capture'} <Radio size={15}/></button></div><div className="hero-orb"><Network size={52}/><span/></div></section><div className="stats"><Stat icon={Boxes} label="Devices" value={String(devices.length)} note="observed on LAN"/><Stat icon={ArrowDown} label="Traffic" value={formatBytes(total)} note="captured packets"/><Stat icon={Activity} label="Packets" value={String(packets.length)} note="recent events"/><Stat icon={Globe2} label="Services" value={String(services.length)} note="identified signals"/></div><div className="grid-two"><section className="panel traffic-panel"><div className="panel-head"><div><div className="eyebrow">LIVE TRAFFIC</div><h3>Packet activity</h3></div><span className="live-badge"><i/> {capture?'LIVE':'IDLE'}</span></div><div className="traffic-total"><b>{formatBytes(total)}</b><span>observed</span></div><Sparkline packets={packets}/><div className="legend"><span><i className="mint"/>Packets</span><span className="muted">Latest {packets.length}</span></div></section><section className="panel"><div className="panel-head"><div><div className="eyebrow">TOP SERVICES</div><h3>What's moving</h3></div></div>{services.length?services.map(([s,n])=><div className="service-mini" key={s}><b>{s}</b><span>{formatBytes(n)}</span><strong>{s==='Unknown'?'—':'Observed'}</strong></div>):<Empty text="Start capture to identify services."/>}</section></div><section className="panel"><div className="panel-head"><div><div className="eyebrow">ACTIVE DEVICES</div><h3>Who's online</h3></div></div><div className="device-row head"><span>DEVICE</span><span>IP ADDRESS</span><span>SERVICE</span><span>TRAFFIC</span></div>{devices.slice(0,6).map(d=><div className="device-row" key={d.ip} onClick={()=>onSelect(d)}><span className="device-name"><i style={{background:d.color}}/>{d.name}</span><span className="muted">{d.ip}</span><span><span className="service-tag">{d.service}</span></span><span>{d.traffic}</span></div>)}</section></div>}
function Sparkline({packets}:{packets:Packet[]}){const heights=Array.from({length:15},(_,i)=>Math.max(18,Math.min(100,20+(packets[i]?.size||i*31)%80)));return <div className="sparkline">{heights.map((h,i)=><span key={i} style={{height:`${h}%`}}/>)}</div>}
function Stat({icon:Icon,label,value,note}:{icon:any;label:string;value:string;note:string}){return <div className="stat"><Icon size={18}/><div><small>{label}</small><b>{value}</b><span>{note}</span></div></div>}
function Devices({devices,query,setQuery,onSelect}:{devices:Device[];query:string;setQuery:(s:string)=>void;onSelect:(d:Device)=>void}){return <div className="content"><div className="toolbar"><div className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search devices..."/></div><button className="filter"><ListFilter size={16}/> Filter</button></div><section className="panel"><div className="device-row head"><span>DEVICE</span><span>IP ADDRESS</span><span>VENDOR</span><span>TRAFFIC</span></div>{devices.map(d=><div className="device-row" key={d.ip} onClick={()=>onSelect(d)}><span className="device-name"><i style={{background:d.color}}/><b>{d.name}</b><small>{d.status}</small></span><span className="muted">{d.ip}</span><span>{d.vendor}</span><span>{d.traffic}</span></div>)}{!devices.length&&<Empty text="No devices found."/>}</section></div>}
function Traffic({packets}:{packets:Packet[]}){const total=packets.reduce((n,p)=>n+p.size,0);return <div className="content"><section className="panel large-chart"><div className="panel-head"><div><div className="eyebrow">LIVE TRAFFIC</div><h3>Observed traffic</h3></div><span className="live-badge"><i/> LIVE</span></div><div className="big-number">{formatBytes(total)} <small>captured</small></div><Sparkline packets={packets}/><div className="traffic-cards"><div><ArrowDown/><small>PACKETS</small><b>{packets.length}</b></div><div><ArrowUp/><small>BYTES</small><b>{formatBytes(total)}</b></div></div></section></div>}
function Packets({packets}:{packets:Packet[]}){return <div className="content"><div className="toolbar"><div className="search"><Search size={17}/><input placeholder="Search packets..."/></div><div className="filter-group"><button className="chip active">All</button><button className="chip">TCP</button><button className="chip">UDP</button><button className="chip">DNS</button><button className="chip">TLS</button></div></div><section className="panel packet-panel"><div className="packet-head"><span>TIME</span><span>SOURCE</span><span>DESTINATION</span><span>PROTO</span><span>SIZE</span></div>{packets.slice(0,100).map((p,i)=><div className="packet-row" key={`${p.timestamp}-${i}`}><span>{p.timestamp}</span><span>{p.source}</span><span>{p.destination}</span><span className="proto">{p.protocol}{p.service!=='Unknown'?` · ${p.service}`:''}</span><span>{formatBytes(p.size)}</span></div>)}{!packets.length&&<Empty text="No packets yet. Start live capture."/>}</section></div>}
function Services({packets}:{packets:Packet[]}){const grouped=packets.reduce<Record<string,{bytes:number;count:number;confidence:number}>>((a,p)=>{const x=a[p.service]||{bytes:0,count:0,confidence:0};x.bytes+=p.size;x.count++;x.confidence=Math.max(x.confidence,p.confidence);a[p.service]=x;return a},{});return <div className="content"><section className="panel"><div className="panel-head"><div><div className="eyebrow">SERVICE DETECTION</div><h3>Recognized services</h3></div><span className="confidence"><ShieldCheck size={15}/> Evidence-based</span></div><div className="service-table head"><span>SERVICE</span><span>PACKETS</span><span>TRAFFIC</span><span>CONFIDENCE</span><span>METHOD</span></div>{Object.entries(grouped).sort((a,b)=>b[1].bytes-a[1].bytes).map(([name,x])=><div className="service-table" key={name}><span className="service-name"><i/>{name}</span><span>{x.count}</span><span>{formatBytes(x.bytes)}</span><span><b className={x.confidence===0?'unknown':''}>{x.confidence?`${x.confidence}%`:'—'}</b></span><span className="muted">DNS / TLS / ports</span></div>)}{!Object.keys(grouped).length&&<Empty text="Service signals appear here as packets are observed."/>}</section></div>}
function Empty({text}:{text:string}){return <div className="empty"><Radio size={24}/><b>{text}</b></div>}
function formatBytes(n:number){if(n<1024)return `${n} B`;if(n<1024*1024)return `${(n/1024).toFixed(1)} KB`;return `${(n/1024/1024).toFixed(1)} MB`}
