const API_BASE="http://127.0.0.1:8765";const $=id=>document.getElementById(id);let previous=null,previousAt=0,historicalSession=null;
function formatBytes(bytes){if(bytes<1024)return `${bytes} B`;const units=["KB","MB","GB"];let value=bytes,unit="B";for(const next of units){value/=1024;unit=next;if(value<1024)break}return `${value.toFixed(value>=100?0:1)} ${unit}`}
function formatRate(bytes,previous,elapsed){if(previous==null||!elapsed)return "0 B/s";return `${formatBytes(Math.max(0,bytes-previous)*1000/elapsed)}/s`}
function stateLabel(state){return({Running:"Capturing",Starting:"Starting…",Stopping:"Stopping…",Failed:"Capture error",Idle:"Idle"})[state]||state}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c])}function formatSessionTime(ms){return new Date(Number(ms)).toLocaleString()}
function render(s){const now=Date.now(),elapsed=now-previousAt;$("capture-status").textContent=historicalSession?"Historical session":stateLabel(s.state);$("capture-status").classList.toggle("ns-status-error",s.state==="Failed");$("capture-device").textContent=s.capture_device||"No adapter";$("device-count").textContent=s.devices.length;$("flow-count").textContent=s.traffic.active_flows;$("download-rate").textContent=historicalSession?formatBytes(s.traffic.bytes):formatRate(s.traffic.bytes,previous?.bytes,elapsed);$("upload-rate").textContent=formatBytes(s.devices.reduce((a,d)=>a+d.bytes_up,0));$("flow-body").innerHTML=s.flows.slice(0,100).map(f=>`<tr><td>${escapeHtml(f.source)}</td><td>${escapeHtml(f.destination)}</td><td><span class="ns-service">${escapeHtml(f.protocol)}</span></td><td>${f.source_port&&f.destination_port?`${f.source_port} → ${f.destination_port}`:"—"}</td><td>${formatBytes(f.bytes)}</td><td>${f.packets}</td></tr>`).join("")||'<tr><td colspan="6" class="ns-empty">No flow data in this session.</td></tr>';$('device-body').innerHTML=s.devices.slice(0,100).map(d=>`<tr><td>${escapeHtml(d.hostname||d.id)}</td><td>${escapeHtml(d.ip||"—")}</td><td>${escapeHtml(d.device_type||"Unknown")}</td><td>${formatBytes(d.bytes_down)}</td><td>${formatBytes(d.bytes_up)}</td><td>${d.confidence}%</td></tr>`).join("")||'<tr><td colspan="6" class="ns-empty">No devices observed.</td></tr>';$('timeline-list').innerHTML=s.timeline.slice(-40).reverse().map(x=>`<div class="ns-timeline-row"><span>${new Date(Number(x.timestamp_ms)).toLocaleTimeString()}</span><strong>${escapeHtml(x.device)}</strong><span>${escapeHtml(x.service)}</span><span>${escapeHtml(x.protocol)}</span><span>${formatBytes(x.bytes_up+x.bytes_down)}</span></div>`).join("")||'<div class="ns-empty">No timeline data.</div>';$('view-subtitle').textContent=historicalSession?`Read-only history: ${escapeHtml(historicalSession)}`:"Live visibility across your connected network.";$('live-button').hidden=!historicalSession;previous=s.traffic;previousAt=now}
function renderDiagnostics(d){if(!d)return;const h=d.health||{};$('diag-received').textContent=h.packets_received??0;$('diag-dropped').textContent=h.packets_dropped??0;$('diag-drop-rate').textContent=`${Number(d.drop_rate_percent||0).toFixed(2)}%`;$('diag-queue').textContent=`${Number(d.queue_utilization_percent||0).toFixed(1)}%`}
async function loadDiagnostics(){try{const r=await fetch(`${API_BASE}/api/diagnostics`,{cache:'no-store'});if(r.ok)renderDiagnostics(await r.json())}catch(_){} }
async function loadSessions(){try{const r=await fetch(`${API_BASE}/api/sessions`,{cache:'no-store'});if(!r.ok)throw 0;const a=await r.json();$('session-list').innerHTML=a.map(s=>`<button class="ns-session" data-session="${escapeHtml(s.id)}"><span><strong>${escapeHtml(s.capture_device)}</strong><small>${formatSessionTime(s.started_at_ms)}</small></span><span class="ns-session-meta"><em class="ns-session-state ${escapeHtml(s.state)}">${escapeHtml(s.state)}</em><small>${s.snapshot_count} snapshots</small></span></button>`).join('')||'<div class="ns-empty">No capture sessions yet.</div>';document.querySelectorAll('.ns-session').forEach(b=>b.onclick=()=>openSession(b.dataset.session))}catch(_){$('session-list').innerHTML='<div class="ns-empty">Session history is available when netsight-agent is running.</div>'}}
async function openSession(id){try{const r=await fetch(`${API_BASE}/api/sessions/${encodeURIComponent(id)}`,{cache:'no-store'});if(!r.ok)throw 0;historicalSession=id;render(await r.json());location.hash='overview'}catch(_){historicalSession=null}}
function returnLive(){historicalSession=null;previous=null;previousAt=0;poll()}
$('live-button').onclick=returnLive;async function poll(){if(historicalSession)return;try{const r=await fetch(`${API_BASE}/api/snapshot`,{cache:'no-store'});if(!r.ok)throw 0;render(await r.json());loadDiagnostics()}catch(_){$('capture-status').textContent='Agent offline';$('capture-status').classList.add('ns-status-error');$('capture-device').textContent='Start netsight-agent on Windows')}}poll();loadSessions();loadDiagnostics();setInterval(poll,500);setInterval(loadSessions,2000);setInterval(loadDiagnostics,1000);
